forum/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^account/login/$', views.LoginView.as_view(), name='login'),
    url(r'^account/logout/$', views.logout_view, name='logout'),
    url(r'^account/registration/$',
        views.RegistrationView.as_view(), name='registration'),
    url(r'^(?P<id>\d+)/$', views.SubCategoryView.as_view(), name='subcategory'),

    url(r'^thread/(?P<id>\d+)/reply-to/(?P<reply_to_id>\d+)$', views.ThreadView.as_view(), name='reply_to_post'),
    url(r'^thread/(?P<id>\d+)/check-new-posts/last_loaded=(?P<last_loaded>\d+\.*\d*)/$', views.CheckNewPostsView.as_view(),
        name='check_new_posts'),
    url(r'^thread/(?P<pk>\d+)/update$', views.ThreadUpdateView.as_view(), name='thread_update'),
    url(r'^thread/(?P<pk>\d+)/delete$', views.ThreadDeleteView.as_view(), name='thread_delete'),
    url(r'^thread/(?P<id>\d+)/$', views.ThreadView.as_view(), name='thread'),

    url(r'^post/(?P<pk>\d+)/update$', views.PostUpdateView.as_view(), name='post_update'),
    url(r'^post/(?P<pk>\d+)/delete$', views.PostDeleteView.as_view(), name='post_delete'),
)

forum_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(''
    , url(r'', include('forum.urls', namespace='forum'))
    , url(r'^admin/', include(admin.site.urls))
)

forum/models.py
from django.db import models
from datetime import datetime
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location="forum/static/media/")


class Category(models.Model):
    name = models.CharField(max_length=1024)
    auth_only = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=1024)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.name


class Thread(models.Model):
    sub_category = models.ForeignKey(SubCategory)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=2048)
    date = models.DateTimeField(default=datetime.utcnow)
    user = models.ForeignKey('auth.User', default=None, null=True)
    user_name = models.CharField(max_length=100, default=None, null=True, blank=True)
    user_email = models.EmailField(max_length=100, default=None, null=True, blank=True)
    image = models.ImageField(storage=fs, upload_to='threads/', default=None, null=True, max_length=1024, blank=True)

    def __str__(self):
        return '{0}: {1}'.format(self.id, self.subject)


class Post(models.Model):
    thread = models.ForeignKey(Thread)
    message = models.CharField(max_length=2048)
    date = models.DateTimeField(default=datetime.utcnow)
    user = models.ForeignKey('auth.User', default=None, null=True)
    user_name = models.CharField(max_length=100, default=None, null=True, blank=True)
    user_email = models.EmailField(max_length=100, default=None, null=True, blank=True)
    parent_post = models.ForeignKey('self', default=None, null=True, blank=True)

    def __str__(self):
        return '{0}: {1}'.format(self.id, self.message)

forum/forms.py
from django import forms
from forum import models
from django.contrib.auth import forms as auth_forms
from django.contrib.auth.models import User


class BaseForumForm(forms.ModelForm):

    def __init__(self, user, *args, **kwargs):
        super(BaseForumForm, self).__init__(*args, **kwargs)
        if user and user.is_authenticated():
            self.set_user(user)

    def set_user(self, user):
        self.instance.user = user
        self.fields['user_name'].initial = user.username
        self.fields['user_name'].widget.attrs['readonly'] = True

        self.fields['user_email'].initial = user.email
        self.fields['user_email'].widget.attrs['readonly'] = True

    class Meta:
        widgets = {
            'message': forms.Textarea(attrs={'cols': 40, 'rows': 5})
        }


class ThreadForm(BaseForumForm):
    class Meta(BaseForumForm.Meta):
        labels = {
            'image': 'Upload image'
        }
        model = models.Thread
        fields = ['subject', 'user_name', 'user_email', 'message', 'image']


class PostForm(BaseForumForm):
    class Meta(BaseForumForm.Meta):
        model = models.Post
        fields = ['user_name', 'user_email', 'message']


class AuthenticationForm(auth_forms.AuthenticationForm):
    """
    Form for authorization by username and email
    """

    def __init__(self, request=None, *args, **kwargs):
        super(AuthenticationForm, self).__init__(request, *args, **kwargs)

        self.fields['username'].label = 'User name / Email'


class UserCreationForm(auth_forms.UserCreationForm):
    """
    Form that creates a user by username or email and
    password.
    """
    email = forms.EmailField(required=True)

    def clean_email(self):
        """
        Validate that the supplied email address is unique.
        """

        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError("A user with that email already exists.")
        return self.cleaned_data['email']

    class Meta(auth_forms.UserCreationForm.Meta):
        fields = ["username", "email"]


class PostUpdateForm(forms.ModelForm):
    def __init__(self, *args,**kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)
        self.fields['parent_post'].queryset = models.Post.objects.filter(thread=self.instance.thread)

    class Meta(BaseForumForm.Meta):
        model = models.Post
        fields = ['thread', 'message', 'parent_post']


class ThreadUpdateForm(forms.ModelForm):
    class Meta(BaseForumForm.Meta):
        model = models.Thread
        fields = ['sub_category', 'subject', 'message', 'image']

forum/views/account_views.py
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.utils.functional import lazy
from django.utils.http import is_safe_url
from django.shortcuts import redirect
from django.views.generic import FormView

from forum import forms, mixins


class LoginView(mixins.AjaxFormMixin, mixins.ModalDialogMixin, FormView):

    template_name = 'forum/account/login.html'
    success_url = lazy(reverse, str)('forum:index')
    form_class = forms.AuthenticationForm

    def form_valid(self, form, **kwargs):
        # Ensure the user-originating redirection url is safe.
        if not is_safe_url(url=self.success_url, host=self.request.get_host()):
            return HttpResponseRedirect(self.request.path)

        login(self.request, form.get_user())

        return super(LoginView, self).form_valid(form)


def logout_view(request, redirect_to=''):
    logout(request)
    if redirect_to:
        return redirect(redirect_to)
    return redirect(reverse('forum:index'))


class RegistrationView(mixins.AjaxFormMixin, mixins.ModalDialogMixin, FormView):

    template_name = 'forum/account/registration.html'
    success_url = lazy(reverse, str)('forum:index')
    form_class = forms.UserCreationForm

    def form_valid(self, form):
        # Ensure the user-originating redirection url is safe.
        if not is_safe_url(url=self.success_url, host=self.request.get_host()):
            return HttpResponseRedirect(self.request.path)

        # Save the new user first
        form.save()
        # Get the username and password
        username = self.request.POST['username']
        password = self.request.POST['password1']

        # Authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)

        return super(RegistrationView, self).form_valid(form)

forum/views/index.py
from django.shortcuts import render
from django.views.generic import View
from forum import models


class Index(View):
    template_name = 'forum/index.html'

    def get(self, request):
        categories = models.Category.objects.all()
        latest_post = models.Post.objects.order_by('date').reverse().all()[0:3]
        return render(request, self.template_name, {'categories': categories, 'latest_post': latest_post})

forum/views/index_view.py
from django.shortcuts import render
from django.views.generic import View
from forum import models
from django.db.models import Max


class IndexView(View):
    template_name = 'forum/index.html'

    def get(self, request):
        categories = models.Category.objects.all()
        latest_threads = models.Thread.objects.annotate(latest_post=Max('post__date'))\
            .order_by(max('latest_post', 'date')).reverse()[0:3]
        return render(request, self.template_name, {'categories': categories, 'latest_threads': latest_threads})

forum/views/index_views.py
from django.shortcuts import render
from django.views.generic import View
from django.db.models import Max

from forum import models


class IndexView(View):
    template_name = 'forum/index.html'

    def get(self, request):
        categories = models.Category.objects.all()
        latest_threads = models.Thread.objects
        if not request.user.is_authenticated():
            latest_threads = latest_threads.filter(sub_category__category__auth_only=0)
        latest_threads = latest_threads.annotate(latest_post=Max('post__date'))\
            .order_by(max('latest_post', 'date')).reverse()[0:3]
        return render(request, self.template_name, {'categories': categories, 'latest_threads': latest_threads})

forum/views/sub_category.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic import View
from forum import models
from forum import forms


class SubCategory(View):
    template_name = 'forum/sub-category.html'

    #TODO login check
    def get(self, request, id):
        return render(request, self.template_name, self._get_context(id, None, request.user))

    #TODO login check
    def post(self, request, id):
        form = forms.ThreadForm(request.POST, request.FILES)
        if not form:
            return HttpResponseRedirect(reverse('forum:index'))

        self._init_form(form, request.user)
        if form.is_valid():
            form.instance.sub_category = get_object_or_404(models.SubCategory, id=id)
            form.save()
            return HttpResponseRedirect(reverse('forum:thread', kwargs={'id': form.instance.id}))

        return render(request, self.template_name, self._get_context(id, form, request.user))

    def _get_context(self, id, form, user):
        subcategory = get_object_or_404(models.SubCategory, id=id)
        categories = models.Category.objects.all()

        if not form:
            form = forms.ThreadForm()
        self._init_form(form, user)

        return {'categories': categories, 'subcategory': subcategory, 'form': form}

    def _init_form(self, form, user):
        if user and user.is_authenticated():
            form.instance.user = user

    # def get(self, request, *args, **kwargs):
    #     subcategory = get_object_or_404(models.SubCategory, id=kwargs['pk'])
    #     categories = models.Category.objects.all()
    #     return render(request, self.template_name, {'categories': categories, 'subcategory': subcategory})


# class SubCategory(DetailView):
#     template_name = 'forum/sub-category.html'
#     queryset = models.SubCategory.objects.all()
#
#     def get_object(self):
#         object = super(SubCategory, self).get_object()
#         return object

    # def get_queryset(self):
    #     self.subcategory = get_object_or_404(models.SubCategory, id=self.kwargs['id'])
    #     return self.subcategory
    # def get(self, request, *args, **kwargs):
    #     try:
    #         subcategory = get_object_or_404(SubCategory, id=kwargs['id'])
    #     except ObjectDoesNotExist:
    #         pass
    #     categories = Category.objects.all()
    #     return render(request, self.template_name, {'categories': categories, 'subcategory': subcategory})

forum/views/sub_category_view.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator

from forum import models
from forum import forms
from forum.views.base_forum_view import BaseForumView
from forum.view_decorators.show_view import sub_category_login_required


class SubCategoryView(BaseForumView):

    template_name = 'forum/sub_category/sub_category.html'


    @method_decorator(sub_category_login_required)
    def dispatch(self, *args, **kwargs):
        return super(SubCategoryView, self).dispatch(*args, **kwargs)

    def get(self, request, id):
        return render(request, self.template_name, self._get_context(id, None, request.user))

    def post(self, request, id):
        form = forms.ThreadForm(request.user, request.POST, request.FILES)
        if not form:
            return HttpResponseRedirect(reverse('forum:index'))

        if form.is_valid():
            form.instance.sub_category = get_object_or_404(models.SubCategory, id=id)
            form.save()
            return HttpResponseRedirect(reverse('forum:thread', kwargs={'id': form.instance.id}))

        return render(request, self.template_name, self._get_context(id, form, request.user))

    def _get_context(self, id, form, user):
        context = super(SubCategoryView, self)._get_context()
        context['sub_category'] = get_object_or_404(models.SubCategory, id=id)

        if not form:
            form = forms.ThreadForm(user)
        context['form'] = form
        return context

forum/views/sub_category_views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import View

from forum import models
from forum import forms
from forum import mixins
from forum.view_decorators.show_view import sub_category_login_required


class SubCategoryView(mixins.CategoriesContextMixin, View):

    template_name = 'forum/sub_category/sub_category.html'

    @method_decorator(sub_category_login_required)
    def dispatch(self, *args, **kwargs):
        return super(SubCategoryView, self).dispatch(*args, **kwargs)

    def get(self, request, id):
        return render(request, self.template_name, self.get_context_data(id, None, request.user))

    def post(self, request, id):
        form = forms.ThreadForm(request.user, request.POST, request.FILES)
        if not form:
            return HttpResponseRedirect(reverse('forum:index'))

        if form.is_valid():
            form.instance.sub_category = get_object_or_404(models.SubCategory, id=id)
            form.save()
            return HttpResponseRedirect(reverse('forum:thread', kwargs={'id': form.instance.id}))

        return render(request, self.template_name, self.get_context_data(id, form, request.user))

    def get_context_data(self, id, form, user):
        context = super(SubCategoryView, self).get_context_data()
        context['sub_category'] = get_object_or_404(models.SubCategory, id=id)

        if not form:
            form = forms.ThreadForm(user)
        context['form'] = form
        return context

forum/views/thread_view.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator

from forum import forms
from forum import models
from forum.views.base_forum_view import BaseForumView
from forum.view_decorators.show_view import thread_login_required


class ThreadView(BaseForumView):

    template_name = 'forum/thread.html'

    @method_decorator(thread_login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadView, self).dispatch(*args, **kwargs)

    def get(self, request, id, reply_to=None):
        return render(request, self.template_name, self._get_context(
            id=id, form=None, user=request.user, reply_to=reply_to))

    def post(self, request, id, reply_to=None):
        form = forms.PostForm(request.user, request.POST, request.FILES)
        if not form:
            return HttpResponseRedirect(reverse('forum:index'))

        if form.is_valid():
            form.instance.thread = get_object_or_404(models.Thread, id=id)
            if reply_to:
                form.instance.parent_post = get_object_or_404(models.Post, id=reply_to)
            form.save()
            return HttpResponseRedirect(reverse('forum:thread', kwargs={'id': id}) + "#" + str(form.instance.id))

        return render(request, self.template_name, self._get_context(
            id=id, form=form, user=request.user, reply_to=reply_to))

    def _get_context(self, id, form, user, reply_to):

        context = super(ThreadView, self)._get_context()
        thread = get_object_or_404(models.Thread, id=id)

        if reply_to:
            post = get_object_or_404(models.Post, id=reply_to)
            if post.thread != thread:
                raise Http404('Post {0} for thread {1} not found'.format(reply_to, id))

        if not form:
            form = forms.PostForm(user)

        context['thread'] = thread
        context['form'] = form
        context['reply_to'] = reply_to
        return context

forum/templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href='{% static 'forum/css/themes/yeti.bootstrap.min.css' %}' />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href='{% static 'forum/css/common.css' %}' />
    <script src="//code.jquery.com/jquery-2.1.3.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="{% static 'forum/scripts/modal_form.js' %}"></script>
    <script src="{% static 'forum/scripts/account.js' %}"></script>

</head>

<body>
    <div class="container">
        {% block header %}{% endblock %}
        {% block content %}{% endblock %}
    {% if not user.is_authenticated %}
        {% include "forum/partial/modal.html" with id='login-form-container' title='Log In' %}
        {% include "forum/partial/modal.html" with id='registration-form-container' title='Registration' %}
    {% endif %}
    </div>


{% block scripts %}{% endblock %}
</body>
</html>

forum/templates/forum/forum_base.html
{% extends 'forum/base.html' %}

{% block header %}
    <!-- HEADER -->
    <div class="row">
        <div class=col-md-12>
            <div class="pull-right">
                <a href="{%  url 'forum:index' %}">Dashboard</a> |
                {% if user.is_authenticated %}
                    <a href="{% url 'forum:logout' %}">Log out</a>
                {% else %}
                    <a href="{% url 'forum:login' %}" id="login">Sign In</a>
                    |
                    <a href="{% url 'forum:registration' %}" id="registration">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            {% load forum_filters %}
            {% for category in categories|filter_by_permissions:user|dictsort:'auth_only' %}
                <p>
                    <strong class="{% if category.auth_only %}text-warning{% endif %}">{{ category.name }}:</strong>
                        {% for subcategory in category.subcategory_set.all %}
                                <a href="{% url "forum:subcategory" subcategory.id %}">{{ subcategory.name }}</a>
                        {% endfor %}
                </p>
            {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="pull-right">
                {% load static %}
                <img class="img-responsive logo" alt="Logo" src="{% static 'forum/images/logo.png' %}" ></imag>
            </div>
        </div>
    </div>

    {% if user.is_superuser %}
        {% include "forum/partial/modal.html" with id='update-thread-form-container' title='Thread update' %}
        {% include "forum/partial/modal.html" with id='update-post-form-container' title='Post update' %}
        {% include "forum/partial/modal.html" with id='delete-form-container' title='Delete' %}
    {% endif %}
{% endblock %}

forum/templates/forum/index.html
{% extends 'forum/base.html' %}
{% block title %}Dashboard{% endblock %}

{% block header %}
    <!-- HEADER -->
    <div class=row>
        <div class="col-md-12" style="padding-right:0">
            <div class="pull-right">
                {% if user.is_authenticated %}
                    <a href="{% url 'forum:logout' %}">Log out</a>
                {% else %}
                    <a href="{% url 'forum:login' %}" id="login">Sign In</a>
                    |
                    <a href="{% url 'forum:registration' %}" id="registration">Sign Up</a>
                {% endif %}
                |
                <a href="/admin">Admin</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            {% load staticfiles %}
            <img class="img-responsive index logo" alt="Logo" src="{% static 'forum/images/logo.png' %}" />
        </div>
        <div class="col-md-10">
            <h1>Forum board</h1>
            {% lorem 1 p %}
        </div>

    </div>
{% endblock %}
    <!-- Content -->
{% block content %}
    <div class="row">
         <div class="col-md-3">
            <div class="bs-component">
                <div class="panel panel-info">
                    <div class="panel-heading">
                      <h3 class="panel-title">Updates</h3>
                    </div>
                    <div class="panel-body">
                        <ul>
                            {% for thread in latest_threads %}
                                <li>
                                    <a href="{% url "forum:subcategory" thread.sub_category.id %}">
                                        [{{ thread.sub_category.name }}]
                                    </a>
                                    <a href="{% url "forum:thread" thread.id %}"> {{ thread.subject }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
             </div>
        </div>
        <div class="col-md-9">
            {% load forum_filters %}
            {% for category in categories|filter_by_permissions:user|dictsort:'auth_only' %}
                <div class="col-md-3">
                    <div class="bs-component">
                        <div class="panel {% if category.auth_only %}panel-warning{% else %}panel-primary{% endif %}">
                            <div class="panel-heading">
                              <h3 class="panel-title">{{ category.name }}</h3>
                            </div>
                            <div class="panel-body">
                                <ul>
                                    {% for subcategory in category.subcategory_set.all %}
                                        <li>
                                            <a href="{% url "forum:subcategory" subcategory.id %}">{{ subcategory.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}